networks:
  basicnet:
    external: true

services:
  prometheus:
    image: prom/prometheus:v3.9.1
    container_name: prometheus
    user: "0"
    command: |
      --web.enable-remote-write-receiver # 启动远程写接收器
      --web.enable-lifecycle # 启动配置重载
    volumes:
      - /data/prometheus-config.yaml:/prometheus/prometheus.yml
      - /data/prometheus-data:/prometheus
      - /var/run/docker.sock:/var/run/docker.sock
    # ports:
    #   - "9090:9090"
    networks:
      - basicnet
    deploy:
      placement:
        constraints:
          - "node.hostname == ${MASTER_HOSTNAME}"
    healthcheck:
      test: ["CMD", "wget", "--tries=1", "--spider", "http://localhost:9090/-/healthy"]
      interval: 10s
      timeout: 5s
      retries: 3
