networks:
  basicnet:
    external: true

services:
  prometheus:
    image: prom/prometheus:v3.9.1
    container_name: prometheus
    user: "0"
    command: |
      --web.enable-remote-write-receiver # 启动远程写接收器
      --web.enable-lifecycle # 启动配置重载
    volumes:
      - /data/prometheus-config.yaml:/prometheus/prometheus.yml
      - /data/prometheus-data:/prometheus
      - /var/run/docker.sock:/var/run/docker.sock
    # ports:
    #   - "9090:9090"
    networks:
      - basicnet
    deploy:
      placement:
        constraints:
          - "node.hostname == ${MASTER_HOSTNAME}"
    healthcheck:
      test: ["CMD", "wget", "--tries=1", "--spider", "http://localhost:9090/-/healthy"]
      interval: 10s
      timeout: 5s
      retries: 3

  # 容器资源监控
  cadvisor:
    image: ghcr.io/google/cadvisor:0.56.2
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /var/run/docker/containerd/containerd.sock:/run/containerd/containerd.sock:ro # !! 这里是 alpine 的位置， 注意各个 linux 系统位置不一样
    # ports:
    #   - 8080:8080
    networks:
      - basicnet
    command: |
      --docker_only=true
    deploy:
      mode: global
      placement:
        constraints: [node.platform.os == linux]